# Generated by Django 5.0 on 2023-12-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekzamen_app', '0002_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='user_id',
        ),
        migrations.AddField(
            model_name='penalty',
            name='penalty_type',
            field=models.CharField(choices=[('penalty1', 'предупреждение'), ('penalty2', 'административный штраф'), ('penalty3', 'лишение прав')], default='penalty1', max_length=10),
        ),
    ]
